config/routes.rb
Rails.application.routes.draw do
  root :to => 'arts#index'
  post '/' => 'arts#index'
  resources :arts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art.rb
class Art < ApplicationRecord
    
    def self.search(search)
        
        if (search[:form] && search[:form] != 'all')
            form_filter = "form='#{search[:form]}'"
        else
            form_filter = "form=form"
        end
        
        if (search[:name] && search[:name] != '')
            name_filter = "name='#{search[:name]}'"
        else
            name_filter = "name=name"
        end

        if (search[:artist] && search[:artist] != '')
            artist_filter = "artist='#{search[:artist]}'"
        else
            artist_filter = "artist=artist"
        end

        sql_query = "SELECT * FROM arts WHERE #{form_filter} AND #{name_filter} AND #{artist_filter};"
        
        Art.find_by_sql sql_query
    end   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  def index
    @arts = Art.search({:form => params[:form],:artist => params[:artist],:name => params[:name]})
  end

  def new
    @art = Art.new
  end

  def create
    art = Art.create art_params
    redirect_to art
  end

  def edit
    @art = Art.find params[:id]
  end

  def update
    art = Art.find params[:id]
    art.update art_params
    redirect_to art    
  end

  def show
    @art = Art.find params[:id]
  end

  def destroy
    art = Art.find params[:id]
    art.destroy
    redirect_to root_path
  end

  private
  def art_params
    params.require(:art).permit(:form, :name, :artist, :year, :image, :search)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/views/arts/_form.html.erb
<div id="add-update-form">
    <%= form_for @art do |f| %>
        <div id="labels">
            <p><%= f.label :form %></p>
            <p><%= f.label :name %></p>
            <p><%= f.label :artist %></p>
            <p><%= f.label :year %></p>
            <p><%= f.label :image %></p>
        </div>
        <div id="inputs">
            <p><%= f.select :form, ["Paint", "Architecture", "Sculpture", "Literature", "Music", "Performance","Cinema"],{ :include_blank => true }, :required => true %></p>
            <p><%= f.text_field :name , :required => true%></p>
            <p><%= f.text_field :artist %></p>
            <p><%= f.number_field :year %></p>
            <p><%= f.text_field :image %></p>
        </div>

        <p id="button-form"><%= f.submit%></p>
    <% end %>
</div>

app/views/arts/_search.html.erb
<%= form_tag( root_path , :method => :post) do %>
    <%= label_tag :form %>
    <%= select_tag :form, raw("
    <option>all</option>
    <option>Paint</option>
    <option>Architecture</option>
    <option>Sculpture</option>
    <option>Literature</option>
    <option>Music</option>
    <option>Performance</option>
    <option>Cinema</option>
    ") %>
    <%= label_tag :name %>
    <%=text_field_tag :name%>
    <%=label_tag :artist %>
    <%=text_field_tag :artist %>
    <%= submit_tag "Search" %>
<% end %>

app/views/arts/edit.html.erb
<div id="form">
    <header>
        <h1>Art-Books</h1>
        <nav>
            <%=link_to "Home", root_path %>
            <%=link_to "back", @art %>
        </nav>
    </header>
    <%= render :partial => 'form' %>
</div>

app/views/arts/index.html.erb
<div id="home">

    <header>
        <h1>Art Books</h1>
        <nav>
            <%=link_to "Home", root_path %>
            <%=link_to "Add", new_art_path %>
        </nav>
    </header>
    <div id="filter">
        <h2>Search Bar</h2>
        <%= render :partial => 'search' %>
    </div>

    <div id="container">

        <% @arts.shuffle.each do |art| %>
            <div id="list">
                <% if art.image.present?%>
                    <a href=<%="/arts/#{art.id}"%>>
                        <img src=<%=art.image%> id="imageHome" />
                    </a>
                <% else %>
                    <%=link_to image_tag("https://via.placeholder.com/200x300?text=#{art.name}"), art %>
                <% end %>
                <p><%=link_to art.name, art%></p>
            </div>
        <% end %>
    </div>
</div>

app/views/arts/new.html.erb
<div id="form">
    <header>
        <h1>Art-Books</h1>
        <nav>
            <%=link_to "Home", root_path %>
            <%=link_to "back", arts_path %>
        </nav>
    </header>
    <%= render :partial => 'form' %>
</div>

app/views/arts/show.html.erb
<div id="art">

    <header>
        <h1>Art Books</h1>
        <nav>
            <%= link_to "Home", arts_path %>
            <%= link_to "Update", edit_art_path %>
            <%= link_to "Delete", @art, :method => 'delete' %>
        </nav>
    </header>

    <div id="art-container">
        <div id="image-div">
            <% if @art.image.present? %>
                <img src=<%=@art.image%> id="art-img" />
            <% else %>
                <%= image_tag "https://via.placeholder.com/400x450?text=#{@art.name}" %>
            <% end %>
        </div>
        <div id="info-div">
            <p>Form: <%=@art.form%></p>
            <p>Name: <%=@art.name%></p>
            <p>Artist: <%=@art.artist%></p>
            <p>Year: <%=@art.year%></p>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Art Books</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>